/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springBootInitialDemo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class App {
	
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
    
    // M12_Milestone1Fase2
    @GetMapping("/")
    public String helloWorld() {
        return "HELLO WORLD!";
    }
    
    @GetMapping("/{nom}")
    public String helloNom(@PathVariable(name="nom") String nom) {
    	return "Hello, " + nom;
    }
    
}
